name: Deploy to Edgeserver.io

on:
  push:
    branches:
      - "main"
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@v0.0.34
        with:
          app_id: "65820895066722304"
          server: https://api.edgeserver.io
          token: ${{ secrets.SIGNAL_TOKEN }}
          directory: .